### ISSUE TITLE
what does gyroai and accelai stands for?

### ISSUE THREAD

**Issue by iceberg1369** [i2Nav-WHU/GIOW-release#1]
hello,

I was looking at the code and I am wondering what does gyroai and accelai stands for?

**Comment by jingshaojing** [comment]
能否麻烦提供一下imu数据bin文件里面的存储顺序？是三轴陀螺的xyz+三轴加计的xyz吗？以及加计的单位？程序里写的m/s?是不是少写了。可以的话能否确认下数据里gps数据后三列的顺序？以及轮速速度和角度那两列的含义

**Comment by forcazzx** [comment]
> 能否麻烦提供一下imu数据bin文件里面的存储顺序？是三轴陀螺的xyz+三轴加计的xyz吗？以及加计的单位？程序里写的m/s?是不是少写了。可以的话能否确认下数据里gps数据后三列的顺序？以及轮速速度和角度那两列的含义

imu与gps的格式请参考https://github.com/i2Nav-WHU/awesome-gins-datasets
陀螺与加计由于是增量的形式，是5ms内陀螺与加计的积分，所以单位是rad和m/s
轮速速度：时间 左轮速度 右轮速度
轮速角度：时间 左轮角度 右轮角度

**Comment by jingshaojing** [comment]
> > 能否麻烦提供一下imu数据bin文件里面的存储顺序？是三轴陀螺的xyz+三轴加计的xyz吗？以及加计的单位？程序里写的m/s?是不是少写了。可以的话能否确认下数据里gps数据后三列的顺序？以及轮速速度和角度那两列的含义
> 
> imu与gps的格式请参考https://github.com/i2Nav-WHU/awesome-gins-datasets 陀螺与加计由于是增量的形式，是5ms内陀螺与加计的积分，所以单位是rad和m/s 轮速速度：时间 左轮速度 右轮速度 轮速角度：时间 左轮角度 右轮角度

多谢
