### ISSUE TITLE
请问一下松耦合部分的代码

### ISSUE THREAD

**Issue by lucianzhong** [i2Nav-WHU/GIOW-release#2]
您好：
       非常感谢博主开源这个项目，但是我这边学习代码的时候对松耦合部分的函数不太理解，请问一下松耦合部分的代码是否能开源？ 非常感谢

**Comment by forcazzx** [comment]
松耦合代码请参考https://github.com/i2Nav-WHU/KF-GINS
也可加入qq群交流481173293

**Comment by forcazzx** [comment]
> 您好： 非常感谢博主开源这个项目，但是我这边学习代码的时候对松耦合部分的函数不太理解，请问一下松耦合部分的代码是否能开源？ 非常感谢

松耦合代码请参考https://github.com/i2Nav-WHU/KF-GINS
也可加入qq群交流481173293

**Comment by lucianzhong** [comment]
收到，感谢
